pipeline {
    agent any
    environment {
        VERSION='0.184'
    }
    stages {
        stage('Prepare env') {
            steps {
                script {
                    env.BRANCH_NAME = 'master'
                    if (env.gitlabSourceBranch != null) {
                        env.BRANCH_NAME = "${env.gitlabSourceBranch}" 
                    }
                    if (env.BRANCH_NAME == 'master') {
                        env.OCI_URI = 'registry-vecps-ns.gaccloud.com.cn/tenant-cgzo'
                    } else {
                        env.OCI_URI = 'registry-vecps-ns.gaccloud.com.cn/tenant-eaws'
                    }
                }
                sh 'echo ${BRANCH_NAME}'
                sh 'echo ${OCI_URI}'
            }
        }
        stage('Build') {
            steps {
                 withCredentials([usernamePassword(credentialsId: 'oci-credentials-prod', usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD')]) {
                    sh '''docker login -u=${USERNAME} -p=${PASSWORD} registry-vecps-ns.gaccloud.com.cn
docker pull ${OCI_URI}/nginx:1.21-alpine
docker pull ${OCI_URI}/node:18
docker tag ${OCI_URI}/node:18 node:18
docker tag ${OCI_URI}/nginx:1.21-alpine nginx:1.21-alpine
docker build -t ${OCI_URI}/cloud_simpro_front:${VERSION} .
'''
                }
            }
        }
        stage('Image Push') {
            steps {
                sh '''docker push ${OCI_URI}/cloud_simpro_front:${VERSION}
docker system prune -f
                '''
            }
        }
        stage('Clean Image') {
            steps {
                sh '''docker rmi ${OCI_URI}/cloud_simpro_front:${VERSION}'''
            }
        }
        stage('Deploy test') {
            when {
                branch 'develop'
            }
            steps {
                withKubeConfig(caCertificate: '', clusterName: '', contextName: '', credentialsId: 'kube-config', namespace:'',restrictKubeConfigAccess: false, serverUrl: ''){
                    sh '''kubectl get pod -owide
envsubst < cicd/cloud-simpro-front.yml | kubectl apply -f -
'''
                }
            }
        }
        stage('Deploy prod') {
            when {
                branch 'master'
                beforeInput true
            }
            options {
                timeout(time:1, unit:'MINUTES')
            }
            input {
                message "是否部署到集群?"
                ok  "是"
            }
            steps {
                withKubeConfig(caCertificate: '', clusterName: '', contextName: '', credentialsId: 'kube-config-prod', namespace:'',restrictKubeConfigAccess: false, serverUrl: ''){
                    sh '''kubectl get pod -owide
envsubst < cicd/cloud-simpro-front.yml | kubectl apply -f -
'''
                }
            }
        }
    }
    post {
        always {
            cleanWs(cleanWhenNotBuilt: false,
                    deleteDirs: true,
                    disableDeferredWipeout: true,
                    notFailBuild: true)
        }
        success {
            echo 'success'
        }
        failure {
            echo 'failure'
        }
    }
}
