pipeline {
    agent any
    environment {
        VERSION='0.5'
        OCI_HOST='harbor.saimo.com:20080'
        OCI_URI='harbor.saimo.com:20080/cloud-simpro'
    }
    stages {
        stage('Build') {
            steps {
                 withCredentials([usernamePassword(credentialsId: 'oci-credentials', usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD')]) {
                    sh '''docker login -u=${USERNAME} -p=${PASSWORD} http://${OCI_HOST}
docker pull ${OCI_URI}/nginx:1.21-alpine
docker pull ${OCI_URI}/node:18
docker tag ${OCI_URI}/node:18 node:18
docker tag ${OCI_URI}/nginx:1.21-alpine nginx:1.21-alpine
docker build -t ${OCI_URI}/cloud_simpro_front:${VERSION} .
'''
                }
            }
        }
        stage('Check') {
            steps {
                echo "Check"
            }
        }
        stage('Image Push') {
            steps {
                sh '''docker push ${OCI_URI}/cloud_simpro_front:${VERSION}
                '''
            }
        }
        stage('Clean Image') {
            steps {
                sh '''docker rmi ${OCI_URI}/cloud_simpro_front:${VERSION}'''
            }
        }
        stage('Deploy') {
            steps {
                withKubeConfig(caCertificate: '', clusterName: '', contextName: '', credentialsId: 'kube-config', namespace:'',restrictKubeConfigAccess: false, serverUrl: ''){
                    sh '''envsubst < cicd/cloud-simpro-front.yml | kubectl apply -f -'''
                }
            }
        }
    }
    post {
        always {
            cleanWs(cleanWhenNotBuilt: false,
                    deleteDirs: true,
                    disableDeferredWipeout: true,
                    notFailBuild: true,
                    patterns: [[pattern: '.gitignore', type: 'INCLUDE'],
                               [pattern: '.propsfile', type: 'EXCLUDE']])
        }
        success {
            echo 'success'
        }
        failure {
            echo 'failure'
        }
    }
}
